version: "3.4"

services:
  api:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: sword_health_api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - rabbit-mq
    networks:
      - dev
    restart: on-failure

  mysql:
    image: mysql
    container_name: mysql_sword_health
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - dev

  rabbit-mq:
    image: rabbitmq:3-management
    hostname: "rabbitmqswordh"
    container_name: rabbitmq_sword_health
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker/rabbitmq:/var/lib/rabbitmq
    networks:
      - dev

networks:
  dev:
    driver: bridge
